export const CATEGORIES = [
  { id: 'todas', name: 'Todas' },
  { id: 'flores', name: '🌼 Flores amarillas' },
  { id: 'mexico', name: '🎉 Independencia de México' },
  { id: 'futbol', name: '⚽ Fútbol' },
  { id: 'gamer', name: '🎮 Gamer' },
  { id: 'amor', name: '❤️ Amor' },
  { id: 'espacio', name: '🌌 Espacio y cielo' },
  { id: 'paisajes', name: '🏞️ Paisajes' },
  { id: 'cumple', name: '🎂 Cumpleaños y fiesta' },
  { id: 'navidad', name: '🎄 Navidad' },
  { id: 'muertos', name: '🕯️ Día de Muertos' },
];

// file: nombre de la escena en js/anim/ (sin .js).
// textPosition: 'top' | 'center'. textDelay: segundos antes de mostrar el mensaje.
// previewLoop: cada cuántos segundos se reinicia en las vistas previas.
export const ANIMATIONS = [
  {
    id: 'corazon-de-energia',
    file: 'corazon-energia',
    category: 'amor',
    title: 'Corazón de energía',
    description: 'Miles de partículas de luz construyen un corazón 3D que late. Tócalo y escribe su nombre.',
    defaultMessage: 'Esto es para ti ❤️',
    textPosition: 'below',
    nameInScene: true,
    interactive: true,
    textDelay: 13.1,
    previewLoop: 22,
  },
  {
    id: 'anillo-de-propuesta',
    file: 'anillo-propuesta',
    category: 'amor',
    title: 'Anillo de propuesta',
    description: 'Toca la cajita de terciopelo y el diamante destella en colores.',
    defaultMessage: '¿Quieres ser mi novia? 💍',
    textPosition: 'top',
    interactive: true,
    textDelay: 4.8,
    previewLoop: 10,
  },
  {
    id: 'constelacion-con-tu-nombre',
    file: 'constelacion-nombre',
    category: 'espacio',
    title: 'Constelación con tu nombre',
    description: 'Las estrellas se unen para escribir su nombre en el cielo.',
    defaultMessage: 'Tu nombre está escrito en mis estrellas ✨',
    textPosition: 'top',
    textDelay: 5.2,
    previewLoop: 12,
  },
  {
    id: 'corazon-pixel-arcade',
    file: 'pixel-corazon',
    category: 'gamer',
    title: 'Corazón pixel arcade',
    description: 'Los bloques caen como en un videojuego retro y arman un corazón.',
    defaultMessage: 'Eres mi player 2 favorito 🕹️',
    textPosition: 'top',
    textDelay: 5,
    previewLoop: 10,
  },
  {
    id: 'corazon-kintsugi',
    file: 'kintsugi',
    category: 'amor',
    title: 'Corazón kintsugi',
    description: 'Un corazón de cristal roto se une y sus grietas se llenan de oro.',
    defaultMessage: 'Contigo hasta lo roto se vuelve más bonito 💛',
    textPosition: 'top',
    textDelay: 5.4,
    previewLoop: 12,
  },
  {
    id: 'esfera-de-nieve',
    file: 'esfera-nieve',
    category: 'navidad',
    title: 'Esfera de nieve',
    description: 'Toca para agitarla: la nieve vuela y se enciende la estrella.',
    defaultMessage: 'Feliz Navidad, eres mi regalo favorito 🎄',
    textPosition: 'top',
    interactive: true,
    textDelay: 4.9,
    previewLoop: 10,
  },
  {
    id: 'arbol-de-navidad',
    file: 'arbol-navidad',
    category: 'navidad',
    title: 'Árbol de Navidad',
    description: 'Las luces suben en espiral hasta encender la estrella.',
    defaultMessage: '¡Feliz Navidad! 🎁',
    textPosition: 'top',
    textDelay: 4.8,
    previewLoop: 11,
  },
  {
    id: 'vela-de-deseo',
    file: 'vela-deseo',
    category: 'cumple',
    title: 'Vela de deseo',
    description: 'Pide un deseo, toca para soplar y el humo se vuelve magia.',
    defaultMessage: 'Que se cumplan todos tus deseos 🕯️',
    textPosition: 'top',
    interactive: true,
    textDelay: 4.8,
    previewLoop: 10,
  },
  {
    id: 'pinata-sorpresa',
    file: 'pinata',
    category: 'cumple',
    title: 'Piñata sorpresa',
    description: 'Dale tres golpes y llueven dulces y confeti.',
    defaultMessage: '¡Feliz cumpleaños! A romperla 🪅',
    textPosition: 'top',
    interactive: true,
    textDelay: 3.8,
    previewLoop: 9,
  },
  {
    id: 'medusas-bioluminiscentes',
    file: 'medusas',
    category: 'paisajes',
    title: 'Medusas bioluminiscentes',
    description: 'Medusas de luz en el fondo del mar y un pulso que lo ilumina todo.',
    defaultMessage: 'Brillas incluso en lo más profundo 💙',
    textPosition: 'top',
    textDelay: 5.6,
    previewLoop: 12,
  },
  {
    id: 'mensaje-en-una-botella',
    file: 'mensaje-botella',
    category: 'paisajes',
    title: 'Mensaje en una botella',
    description: 'Una botella llega flotando y su pergamino se abre en el aire.',
    defaultMessage: 'Cruzaría océanos por ti 🌊',
    textPosition: 'top',
    textDelay: 6,
    previewLoop: 12,
  },
  {
    id: 'luciernagas-en-el-bosque',
    file: 'luciernagas-bosque',
    category: 'paisajes',
    title: 'Luciérnagas en el bosque',
    description: 'Cientos de luciérnagas se sincronizan y brillan en forma de corazón.',
    defaultMessage: 'Iluminas hasta mis noches más oscuras ✨',
    textPosition: 'top',
    textDelay: 5.8,
    previewLoop: 12,
  },
  {
    id: 'globo-aerostatico',
    file: 'globo-aerostatico',
    category: 'paisajes',
    title: 'Globo aerostático',
    description: 'Un globo sube sobre un mar de nubes justo cuando sale el sol.',
    defaultMessage: 'Contigo siento que vuelo 🎈',
    textPosition: 'top',
    textDelay: 5,
    previewLoop: 12,
  },
  {
    id: 'cerezo-en-flor',
    file: 'cerezo-flor',
    category: 'paisajes',
    title: 'Cerezo en flor',
    description: 'El cerezo florece y el viento forma un corazón de pétalos.',
    defaultMessage: 'Contigo todo florece 🌸',
    textPosition: 'top',
    textDelay: 5.6,
    previewLoop: 12,
  },
  {
    id: 'faroles-al-cielo',
    file: 'faroles-cielo',
    category: 'paisajes',
    title: 'Faroles al cielo',
    description: 'Cientos de faroles suben desde el lago en la noche.',
    defaultMessage: 'Eres mi luz en la oscuridad 🏮',
    textPosition: 'top',
    textDelay: 5.4,
    previewLoop: 12,
  },
  {
    id: 'lluvia-en-la-ventana',
    file: 'lluvia-ventana',
    category: 'paisajes',
    title: 'Lluvia en la ventana',
    description: 'Un dedo dibuja un corazón en el vidrio empañado y cae un relámpago.',
    defaultMessage: 'Hasta los días de lluvia son bonitos contigo 🌧️',
    textPosition: 'top',
    textDelay: 5.2,
    previewLoop: 12,
  },
  {
    id: 'atardecer-en-la-playa',
    file: 'atardecer-playa',
    category: 'paisajes',
    title: 'Atardecer en la playa',
    description: 'El sol se hunde en el mar y aparece un corazón en la arena.',
    defaultMessage: 'Quiero todos mis atardeceres contigo 🌅',
    textPosition: 'top',
    textDelay: 6,
    previewLoop: 13,
  },
  {
    id: 'galaxia-espiral',
    file: 'galaxia-espiral',
    category: 'espacio',
    title: 'Galaxia espiral',
    description: 'Miles de estrellas forman una galaxia y su núcleo estalla en luz.',
    defaultMessage: 'Eres mi universo entero 🌌',
    textPosition: 'top',
    textDelay: 5,
    previewLoop: 12,
  },
  {
    id: 'planeta-con-anillos',
    file: 'planeta-anillos',
    category: 'espacio',
    title: 'Planeta con anillos',
    description: 'Un planeta con lunas y un amanecer que ilumina sus anillos.',
    defaultMessage: 'Contigo estoy en otro planeta 🪐',
    textPosition: 'top',
    textDelay: 5.2,
    previewLoop: 12,
  },
  {
    id: 'lluvia-de-estrellas-fugaces',
    file: 'estrellas-fugaces',
    category: 'espacio',
    title: 'Lluvia de estrellas fugaces',
    description: 'Bajo la Vía Láctea cae una lluvia de estrellas y un gran bólido.',
    defaultMessage: 'Todos mis deseos llevan tu nombre 🌠',
    textPosition: 'top',
    textDelay: 5.2,
    previewLoop: 12,
  },
  {
    id: 'aurora-boreal',
    file: 'aurora-boreal',
    category: 'espacio',
    title: 'Aurora boreal',
    description: 'Cortinas de luz sobre montañas nevadas y un lago congelado.',
    defaultMessage: 'Eres la luz más bonita de mi cielo 💚',
    textPosition: 'top',
    textDelay: 5.2,
    previewLoop: 12,
  },
  {
    id: 'carta-de-cristal',
    file: 'carta-cristal',
    category: 'amor',
    title: 'Carta de cristal',
    description: 'Toca el sobre de cristal y sale una carta que se escribe sola.',
    defaultMessage: 'Tengo algo que decirte… te quiero 💌',
    textPosition: 'top',
    interactive: true,
    textDelay: 4.8,
    previewLoop: 11,
  },
  {
    id: 'rosa-roja-creciendo',
    file: 'rosa-roja-creciendo',
    category: 'amor',
    title: 'Rosa roja creciendo',
    description: 'Crece de la tierra al amanecer y florece en terciopelo.',
    defaultMessage: 'Mi amor por ti crece cada día 🌹',
    textPosition: 'top',
    textDelay: 6.2,
    previewLoop: 12,
  },
  {
    id: 'mariposas-neon',
    file: 'mariposas-neon',
    category: 'amor',
    title: 'Mariposas de neón',
    description: 'Mariposas de luz que se unen para encender un corazón.',
    defaultMessage: 'Me haces sentir mariposas 🦋',
    textPosition: 'top',
    textDelay: 5.6,
    previewLoop: 12,
  },
  {
    id: 'latido-de-corazon',
    file: 'latido-corazon',
    category: 'amor',
    title: 'Latido de corazón',
    description: 'El monitor se detiene… y el latido dibuja un corazón.',
    defaultMessage: 'Mi corazón late por ti ❤️',
    textPosition: 'top',
    textDelay: 5.8,
    previewLoop: 11,
  },
  {
    id: 'fuegos-con-tu-nombre',
    file: 'fuegos-nombre',
    category: 'cumple',
    title: 'Fuegos artificiales con tu nombre',
    description: 'Los fuegos estallan y escriben su nombre en el cielo.',
    defaultMessage: 'Iluminas mi vida ✨',
    textPosition: 'top',
    textDelay: 4.6,
    previewLoop: 12,
  },
  {
    id: 'luna-3d',
    file: 'luna-3d',
    category: 'espacio',
    title: 'Luna 3D',
    description: 'La luna sale, gira y se vuelve llena sobre el lago.',
    defaultMessage: 'Te quiero hasta la luna y de regreso 🌙',
    textPosition: 'top',
    textDelay: 5,
    previewLoop: 12,
  },
  {
    id: 'regalo-sorpresa-3d',
    file: 'regalo',
    category: 'cumple',
    title: 'Regalo sorpresa 3D',
    description: 'Toca la caja y descubre lo que hay dentro.',
    defaultMessage: '¡Sorpresa! Esto es para ti 🎁',
    textPosition: 'top',
    // Interactiva: el mensaje sale cuando la escena lo indica; textDelay se usa si se abre sola (grabador).
    interactive: true,
    textDelay: 3.9,
    previewLoop: 10,
  },
  {
    id: 'rosa-de-cristal',
    file: 'rosa-cristal',
    category: 'amor',
    title: 'Rosa de cristal',
    description: 'Florece en la oscuridad con luz dorada y un giro final.',
    defaultMessage: '❤️',
    textPosition: 'top',
    textDelay: 6.6,
    previewLoop: 11,
  },
  {
    id: 'rosa-amarilla',
    file: 'rosa-amarilla',
    category: 'flores',
    title: 'Rosa amarilla realista',
    description: 'Una rosa que se abre pétalo a pétalo, con gotas de rocío.',
    defaultMessage: 'Eres mi persona favorita 💛',
    textPosition: 'top',
    textDelay: 3.8,
    previewLoop: 12,
  },
  {
    id: 'campo-de-girasoles',
    file: 'campo-girasoles',
    category: 'flores',
    title: 'Campo de girasoles al atardecer',
    description: 'Cientos de girasoles meciéndose con la luz dorada.',
    defaultMessage: 'Contigo todo brilla más ☀️',
    textPosition: 'top',
    textDelay: 2.6,
    previewLoop: 14,
  },
  {
    id: 'flores-amarillas-con-rocio',
    file: 'flores-rocio',
    category: 'flores',
    title: 'Flores amarillas con rocío',
    description: 'Vista macro con gotas que brillan y cambio de enfoque.',
    defaultMessage: 'Florezco cada vez que pienso en ti 🌼',
    textPosition: 'top',
    textDelay: 3.2,
    previewLoop: 12,
  },
  {
    id: 'ramo-flores-amarillas',
    file: 'ramo',
    category: 'flores',
    title: 'Ramo de flores amarillas',
    description: 'Un ramo que florece frente a sus ojos.',
    defaultMessage: 'Te regalo estas flores amarillas 💛',
    textPosition: 'top',
    textDelay: 3.6,
    previewLoop: 12,
  },
  {
    id: 'girasol',
    file: 'girasol',
    category: 'flores',
    title: 'Girasol que florece',
    description: 'Un girasol que se abre pétalo a pétalo.',
    defaultMessage: 'Eres el sol que ilumina mis días 🌻',
    textPosition: 'top',
    textDelay: 4.2,
    previewLoop: 12,
  },
  {
    id: 'corazon-flores',
    file: 'corazon',
    category: 'flores',
    title: 'Corazón de flores amarillas',
    description: 'Decenas de florecitas forman un corazón.',
    defaultMessage: 'Mi corazón florece contigo',
    textPosition: 'top',
    textDelay: 4,
    previewLoop: 11,
  },
  {
    id: 'tulipanes-amarillos',
    file: 'tulipanes',
    category: 'flores',
    title: 'Tulipanes amarillos al amanecer',
    description: 'Tulipanes que crecen y se abren con el sol.',
    defaultMessage: 'Para ti, que alegras mis días 🌷',
    textPosition: 'top',
    textDelay: 3.2,
    previewLoop: 11,
  },
  {
    id: 'fuegos-viva-mexico',
    file: 'fuegos',
    category: 'mexico',
    title: 'Fuegos artificiales ¡Viva México!',
    description: 'Pirotecnia verde, blanco y rojo sobre la ciudad.',
    defaultMessage: '¡Viva México!',
    textPosition: 'center',
    textDelay: 1.5,
    previewLoop: 20,
  },
  {
    id: 'papel-picado',
    file: 'papel-picado',
    category: 'mexico',
    title: 'Papel picado y confeti',
    description: 'Fiesta mexicana para celebrar el 15 de septiembre.',
    defaultMessage: '¡Feliz Día de la Independencia! 🎉',
    textPosition: 'center',
    textDelay: 1.8,
    previewLoop: 14,
  },
  {
    id: 'tiro-libre-al-angulo',
    file: 'tiro-libre',
    category: 'futbol',
    title: 'Tiro libre al ángulo',
    description: 'Carrerita, disparo con efecto y golazo en el estadio.',
    defaultMessage: '¡Golazo! Eres el mejor ⚽',
    textPosition: 'top',
    textDelay: 4.6,
    previewLoop: 9,
  },
  {
    id: 'chilena-bajo-la-lluvia',
    file: 'chilena',
    category: 'futbol',
    title: 'Chilena bajo la lluvia',
    description: 'Una chilena en cámara lenta bajo los reflectores.',
    defaultMessage: 'Eres un crack dentro y fuera de la cancha 🏆',
    textPosition: 'top',
    textDelay: 3.4,
    previewLoop: 8,
  },
  {
    id: 'mira-tactica',
    file: 'mira-tactica',
    category: 'gamer',
    title: 'Mira táctica: 3 de 3',
    description: 'Estilo shooter: apunta, dispara y gana la partida.',
    defaultMessage: '¡Eres mi MVP! 🏆',
    textPosition: 'top',
    textDelay: 3.6,
    previewLoop: 8,
  },
  {
    id: 'gol-ultimo-minuto',
    file: 'gol',
    category: 'futbol',
    title: '¡Gol de último minuto!',
    description: 'Estilo fútbol: un golazo en el estadio lleno.',
    defaultMessage: '¡GOOOL! Eres un crack ⚽',
    textPosition: 'top',
    textDelay: 1.9,
    previewLoop: 9,
  },
  {
    id: 'carrera-neon',
    file: 'carrera-neon',
    category: 'gamer',
    title: 'Carrera nocturna neón',
    description: 'Estilo autos: velocidad por una carretera retro.',
    defaultMessage: 'Contigo, a toda velocidad 🏁',
    textPosition: 'top',
    textDelay: 2.2,
    previewLoop: 14,
  },
  {
    id: 'aura-de-poder',
    file: 'aura-poder',
    category: 'gamer',
    title: 'Aura de poder al máximo',
    description: 'Estilo anime: energía que se carga y explota.',
    defaultMessage: '¡Tu poder está al máximo! 🔥',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 9,
  },
  {
    id: 'subiste-de-nivel',
    file: 'level-up',
    category: 'gamer',
    title: '¡Subiste de nivel!',
    description: 'Estilo arcade: la barra de experiencia se llena.',
    defaultMessage: 'Feliz cumpleaños, nuevo nivel desbloqueado 🎮',
    textPosition: 'top',
    textDelay: 3.4,
    previewLoop: 9,
  },
  {
    id: 'cofre-legendario',
    file: 'cofre',
    category: 'gamer',
    title: 'Cofre legendario',
    description: 'Estilo videojuego: abre un cofre lleno de premios.',
    defaultMessage: 'Eres mi premio legendario 💎',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 9,
  },
  {
    id: 'lluvia-de-corazones',
    file: 'lluvia-corazones',
    category: 'amor',
    title: 'Lluvia de corazones',
    description: 'Corazones que flotan alrededor de un gran corazón.',
    defaultMessage: 'Te quiero muchísimo ❤️',
    textPosition: 'center',
    textDelay: 1.4,
    previewLoop: 12,
  },
  {
    id: 'constelacion-de-corazon',
    file: 'constelacion',
    category: 'amor',
    title: 'Constelación de corazón',
    description: 'Las estrellas se unen para formar un corazón.',
    defaultMessage: 'Eres mi estrella favorita ✨',
    textPosition: 'top',
    textDelay: 4,
    previewLoop: 12,
  },
  {
    id: 'pastel-de-cumpleanos',
    file: 'pastel',
    category: 'cumple',
    title: 'Pastel de cumpleaños',
    description: 'Velitas encendidas y lluvia de confeti.',
    defaultMessage: '¡Feliz cumpleaños! 🎂',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 12,
  },
  {
    id: 'globos-de-cumpleanos',
    file: 'globos',
    category: 'cumple',
    title: 'Globos de cumpleaños',
    description: 'Globos de colores que suben al cielo.',
    defaultMessage: '¡Que cumplas muchos más! 🎈',
    textPosition: 'center',
    textDelay: 2,
    previewLoop: 14,
  },
  {
    id: 'arco-de-cempasuchil',
    file: 'cempasuchil',
    category: 'muertos',
    title: 'Arco de cempasúchil',
    description: 'Flores de cempasúchil, velas y mariposas monarca.',
    defaultMessage: 'Siempre en nuestro corazón 🧡',
    textPosition: 'top',
    textDelay: 3.2,
    previewLoop: 12,
  },
];

for (const anim of ANIMATIONS) anim.load = () => import(`./anim/${anim.file}.js`);

export const getAnimation = (id) => ANIMATIONS.find((a) => a.id === id);
export const getCategory = (id) => CATEGORIES.find((c) => c.id === id);
