export const CATEGORIES = [
  { id: 'todas', name: 'Todas' },
  { id: 'flores', name: '🌼 Flores amarillas' },
  { id: 'mexico', name: '🎉 Independencia de México' },
  { id: 'gamer', name: '🎮 Gamer' },
  { id: 'amor', name: '❤️ Amor' },
  { id: 'cumple', name: '🎂 Cumpleaños' },
  { id: 'muertos', name: '🕯️ Día de Muertos' },
];

// file: nombre de la escena en js/anim/ (sin .js).
// textPosition: 'top' | 'center'. textDelay: segundos antes de mostrar el mensaje.
// previewLoop: cada cuántos segundos se reinicia en las vistas previas.
export const ANIMATIONS = [
  {
    id: 'ramo-flores-amarillas',
    file: 'ramo',
    category: 'flores',
    title: 'Ramo de flores amarillas',
    description: 'Un ramo que florece frente a sus ojos.',
    defaultMessage: 'Te regalo estas flores amarillas 💛',
    textPosition: 'top',
    textDelay: 3.6,
    previewLoop: 12,
  },
  {
    id: 'girasol',
    file: 'girasol',
    category: 'flores',
    title: 'Girasol que florece',
    description: 'Un girasol que se abre pétalo a pétalo.',
    defaultMessage: 'Eres el sol que ilumina mis días 🌻',
    textPosition: 'top',
    textDelay: 4.2,
    previewLoop: 12,
  },
  {
    id: 'corazon-flores',
    file: 'corazon',
    category: 'flores',
    title: 'Corazón de flores amarillas',
    description: 'Decenas de florecitas forman un corazón.',
    defaultMessage: 'Mi corazón florece contigo',
    textPosition: 'top',
    textDelay: 4,
    previewLoop: 11,
  },
  {
    id: 'tulipanes-amarillos',
    file: 'tulipanes',
    category: 'flores',
    title: 'Tulipanes amarillos al amanecer',
    description: 'Tulipanes que crecen y se abren con el sol.',
    defaultMessage: 'Para ti, que alegras mis días 🌷',
    textPosition: 'top',
    textDelay: 3.2,
    previewLoop: 11,
  },
  {
    id: 'fuegos-viva-mexico',
    file: 'fuegos',
    category: 'mexico',
    title: 'Fuegos artificiales ¡Viva México!',
    description: 'Pirotecnia verde, blanco y rojo sobre la ciudad.',
    defaultMessage: '¡Viva México!',
    textPosition: 'center',
    textDelay: 1.5,
    previewLoop: 20,
  },
  {
    id: 'papel-picado',
    file: 'papel-picado',
    category: 'mexico',
    title: 'Papel picado y confeti',
    description: 'Fiesta mexicana para celebrar el 15 de septiembre.',
    defaultMessage: '¡Feliz Día de la Independencia! 🎉',
    textPosition: 'center',
    textDelay: 1.8,
    previewLoop: 14,
  },
  {
    id: 'mira-tactica',
    file: 'mira-tactica',
    category: 'gamer',
    title: 'Mira táctica: 3 de 3',
    description: 'Estilo shooter: apunta, dispara y gana la partida.',
    defaultMessage: '¡Eres mi MVP! 🏆',
    textPosition: 'top',
    textDelay: 3.6,
    previewLoop: 8,
  },
  {
    id: 'gol-ultimo-minuto',
    file: 'gol',
    category: 'gamer',
    title: '¡Gol de último minuto!',
    description: 'Estilo fútbol: un golazo en el estadio lleno.',
    defaultMessage: '¡GOOOL! Eres un crack ⚽',
    textPosition: 'top',
    textDelay: 1.9,
    previewLoop: 9,
  },
  {
    id: 'carrera-neon',
    file: 'carrera-neon',
    category: 'gamer',
    title: 'Carrera nocturna neón',
    description: 'Estilo autos: velocidad por una carretera retro.',
    defaultMessage: 'Contigo, a toda velocidad 🏁',
    textPosition: 'top',
    textDelay: 2.2,
    previewLoop: 14,
  },
  {
    id: 'aura-de-poder',
    file: 'aura-poder',
    category: 'gamer',
    title: 'Aura de poder al máximo',
    description: 'Estilo anime: energía que se carga y explota.',
    defaultMessage: '¡Tu poder está al máximo! 🔥',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 9,
  },
  {
    id: 'subiste-de-nivel',
    file: 'level-up',
    category: 'gamer',
    title: '¡Subiste de nivel!',
    description: 'Estilo arcade: la barra de experiencia se llena.',
    defaultMessage: 'Feliz cumpleaños, nuevo nivel desbloqueado 🎮',
    textPosition: 'top',
    textDelay: 3.4,
    previewLoop: 9,
  },
  {
    id: 'cofre-legendario',
    file: 'cofre',
    category: 'gamer',
    title: 'Cofre legendario',
    description: 'Estilo videojuego: abre un cofre lleno de premios.',
    defaultMessage: 'Eres mi premio legendario 💎',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 9,
  },
  {
    id: 'lluvia-de-corazones',
    file: 'lluvia-corazones',
    category: 'amor',
    title: 'Lluvia de corazones',
    description: 'Corazones que flotan alrededor de un gran corazón.',
    defaultMessage: 'Te quiero muchísimo ❤️',
    textPosition: 'center',
    textDelay: 1.4,
    previewLoop: 12,
  },
  {
    id: 'constelacion-de-corazon',
    file: 'constelacion',
    category: 'amor',
    title: 'Constelación de corazón',
    description: 'Las estrellas se unen para formar un corazón.',
    defaultMessage: 'Eres mi estrella favorita ✨',
    textPosition: 'top',
    textDelay: 4,
    previewLoop: 12,
  },
  {
    id: 'pastel-de-cumpleanos',
    file: 'pastel',
    category: 'cumple',
    title: 'Pastel de cumpleaños',
    description: 'Velitas encendidas y lluvia de confeti.',
    defaultMessage: '¡Feliz cumpleaños! 🎂',
    textPosition: 'top',
    textDelay: 3,
    previewLoop: 12,
  },
  {
    id: 'globos-de-cumpleanos',
    file: 'globos',
    category: 'cumple',
    title: 'Globos de cumpleaños',
    description: 'Globos de colores que suben al cielo.',
    defaultMessage: '¡Que cumplas muchos más! 🎈',
    textPosition: 'center',
    textDelay: 2,
    previewLoop: 14,
  },
  {
    id: 'arco-de-cempasuchil',
    file: 'cempasuchil',
    category: 'muertos',
    title: 'Arco de cempasúchil',
    description: 'Flores de cempasúchil, velas y mariposas monarca.',
    defaultMessage: 'Siempre en nuestro corazón 🧡',
    textPosition: 'top',
    textDelay: 3.2,
    previewLoop: 12,
  },
];

for (const anim of ANIMATIONS) anim.load = () => import(`./anim/${anim.file}.js`);

export const getAnimation = (id) => ANIMATIONS.find((a) => a.id === id);
export const getCategory = (id) => CATEGORIES.find((c) => c.id === id);
