import { TURTLE_ANIMATIONS } from './turtle-catalog.js';
export const CATEGORY_GUIDES = {
  'expert-zone':{intro:'Experiencias 3D de autor, con geometrías, materiales e iluminación desarrollados para cada obra. Personaliza y comparte la escena completa; su código fuente no se ofrece como un único HTML.',picks:[['eternal-bloom','Una rosa translúcida se ensambla y florece bajo una luz dorada que recorre sus pétalos.'],['soul-butterfly','Una mariposa de alas curvas emprende un vuelo y convierte sus partículas en palabras.'],['event-horizon','Un disco de plasma con espesor rodea un horizonte oscuro que curva la luz del campo estelar.'],['crystal-heartbeat','Fragmentos curvos se fusionan en un corazón de cristal con energía interior y un latido doble.']],advice:'Las nuevas miniaturas alternan una vista animada de calidad reducida con imágenes representativas: acerca el puntero o enfoca una tarjeta para verla viva. Eternal Bloom conserva su miniatura estática. Abre cada ficha para reproducir la secuencia completa. La calidad se adapta al dispositivo y se respeta movimiento reducido. El código fuente figura como Próximamente: no hay compras ni desbloqueos disponibles.'},
  flores: { intro:'Elige entre una flor que se abre sola, una figura que cambia al tocarla y un recorrido con recuerdos. El amarillo es parte del diseño de muchas escenas; solo las que muestran el selector de color permiten modificar su paleta.', picks:[['ramo-flores-amarillas','Para enviar un ramo sin pedir interacción: las flores se abren por etapas y el mensaje queda sobre la escena.'],['corazon-de-girasoles','Si quieres revelar un nombre con la propia animación: el corazón floral se transforma en letras después del toque.'],['jardin-de-lunas','Para una carta y varios recuerdos: el viaje pasa por siete islas antes del corazón final. Es un recorrido más largo que una floración.']], advice:'En Origami amarillo el mensaje se dibuja dentro de una tarjeta de cinco líneas: funciona mejor una frase corta. En Flor de luz interactiva el destinatario mantiene pulsado para hacer crecer la flor; en Girasol o Rosa amarilla basta con mirar.' },
  halloween: { intro:'Estas escenas reúnen partículas en figuras de Halloween y las dispersan con un toque. Puedes elegir una frase de temporada, escribir la tuya o dejar únicamente la figura, sin dedicatoria.', picks:[['fantasmita-rosa','Para un saludo amable: un fantasma de luz rosa con mejillas y movimiento flotante.'],['pocion-de-luz','Para una invitación: la botella de poción admite un título como el nombre de la fiesta.'],['luna-de-murcielagos','Para un tono más nocturno: una luna creciente y siluetas de murciélagos sobre fondo oscuro.']], advice:'Todas permiten un título opcional, cinco tipografías para el texto normal y dos colores. Con un título, las partículas forman letras; en Sin texto, regresan a la figura. Elige el texto según sea una felicitación o una invitación del 31 de octubre.' },
  muertos: { intro:'Para el 1 y 2 de noviembre, distingue entre una figura de recuerdo, una ofrenda colectiva y una escena dedicada a una mascota. Elige una frase acorde con quien recibirá el enlace; no es necesario convertir el recuerdo en una dedicatoria romántica.', picks:[['ofrenda-de-luz','Para compartir una ofrenda con la familia: reúne niveles, velas, flores y papel picado.'],['huellitas-al-mictlan','Para recordar a una mascota: el perrito de luz aparece sobre un camino de flores.'],['arco-de-cempasuchil','Si prefieres que se reproduzca sola: el arco mantiene flores, velas y monarcas sin una transformación por toque.']], advice:'Las cinco escenas nuevas admiten frase sugerida, texto libre o Sin texto, además de título y colores. Arco de cempasúchil conserva su paleta y el formulario de nombre, mensaje y firma. Monarca del recuerdo se centra en el vuelo; Calaverita de colores, en una figura festiva.' },
  mexico: { intro:'Aquí hay dos formas de acompañar un saludo para el 15 y 16 de septiembre: pirotecnia sobre la ciudad o banderitas que mantienen el ambiente de fiesta. Ambas se reproducen sin que el destinatario tenga que intervenir.', picks:[['fuegos-viva-mexico','Para una celebración nocturna: combina estallidos tricolor con otros fuegos dorados.'],['papel-picado','Para un saludo de fiesta: las tiras de banderitas se mueven de forma continua.']], advice:'Los colores de estas dos escenas se conservan para mantener su diseño. El nombre, la frase y la firma se muestran como texto sobre la composición: no se escriben con los fuegos ni se recortan dentro del papel.' },
  futbol: { intro:'Elige la jugada que mejor acompañe tu mensaje: un tiro libre con portero, una chilena bajo la lluvia o un balón que llega a la red. Son escenas de fútbol para mirar, no minijuegos para controlar.', picks:[['tiro-libre-al-angulo','Para mostrar una jugada completa: carrera, disparo, salto del portero y llegada a la red.'],['chilena-bajo-la-lluvia','Para destacar la técnica del salto: contacto con el balón y caída con lluvia y reflectores.'],['gol-ultimo-minuto','Para una felicitación por una victoria: la red se deforma al recibir el balón.']], advice:'Puedes editar el nombre, el mensaje, la firma y su tipografía. Las camisetas, la trayectoria del balón y el resultado forman parte del diseño; el editor no ofrece elección de club o de futbolista.' },
  gamer: { intro:'Estas animaciones usan el lenguaje visual de videojuegos: bloques, barras de experiencia, recompensas, miras y carreteras retro. La escena es automática; la personalización está en tu mensaje.', picks:[['subiste-de-nivel','Para felicitar por un logro o un cumpleaños: una barra se completa y cambia el nivel decorativo.'],['cofre-legendario','Para presentar una sorpresa: la tapa del cofre se abre y deja salir gemas. No entrega premios reales.'],['carrera-neon','Para alguien que disfruta los coches: una carretera retro recorre el fondo de un automóvil.']], advice:'Corazón pixel arcade combina los bloques con una figura afectuosa. Mira táctica muestra tres disparos automáticos, y Aura de poder acumula luz hasta un estallido. No necesitan acceso a cuentas de juegos ni muestran estadísticas reales.' },
  amor: { intro:'Piensa primero en el tipo de sorpresa: una apertura con un toque, una floración tranquila o un nombre que se forme con luz. Las escenas admiten una frase propia para que el tono lo decidas tú.', picks:[['corazon-de-energia','Para revelar un nombre con partículas: el corazón late antes de transformarse en letras.'],['carta-de-cristal','Para una nota breve: se abre un sobre transparente y el mensaje aparece sobre la escena.'],['rosa-roja-creciendo','Para mirar sin tocar: el tallo crece y la rosa se abre bajo luz de amanecer.']], advice:'Anillo de propuesta presenta una pregunta elegida por ti, sin un formulario de respuesta. Mariposas neón y Lluvia de corazones permiten modificar dos colores; Corazón kintsugi conserva las grietas doradas de su diseño.' },
  espacio: { intro:'El cielo puede ser el fondo de una frase o la figura que escribe el nombre. Elige una constelación de letras si quieres personalizar el protagonista; elige un planeta, una galaxia o una aurora si prefieres acompañar el texto con un paisaje.', picks:[['constelacion-con-tu-nombre','Para un nombre breve: las estrellas forman letras y trazan líneas entre ellas.'],['planeta-con-anillos','Para una escena de profundidad: anillos y lunas acompañan el amanecer en el borde de un planeta.'],['aurora-boreal','Para una felicitación más serena: cortinas de luz sobre montañas y un lago.']], advice:'Galaxia espiral concentra su efecto en el destello del núcleo. Lluvia de estrellas fugaces incluye un bólido más brillante y Luna 3D cambia su iluminación sobre el agua. Todas avanzan solas y no representan el cielo en tiempo real.' },
  paisajes: { intro:'Elige el ambiente que acompañe tu frase: bosque y luciérnagas, mar con medusas, lluvia urbana, playa, nubes o faroles. En esta categoría las escenas avanzan solas, sin un gesto necesario para abrir el mensaje.', picks:[['medusas-bioluminiscentes','Para un ambiente marino oscuro: las medusas se iluminan y permiten escoger dos colores.'],['lluvia-en-la-ventana','Para un tono íntimo: gotas, luces de ciudad, un corazón en el vaho y un relámpago.'],['atardecer-en-la-playa','Para evocar una orilla: el sol baja y la ola descubre un corazón en la arena.']], advice:'Cerezo en flor y Luciérnagas en el bosque reúnen elementos del paisaje en un corazón. Mensaje en una botella entrega un pergamino, pero la frase editable es breve y se muestra encima de la escena. Para una carta larga, busca los recorridos con carta en Flores.' },
  cumple: { intro:'Para felicitar puedes elegir una celebración que avance sola o una sorpresa que la persona abra. La vela pide un toque, la piñata admite tres golpes y el regalo descubre un corazón al abrirse.', picks:[['pinata-sorpresa','Para participar en la felicitación: tres toques separados agrietan y rompen la piñata.'],['vela-de-deseo','Para un deseo: un toque apaga la llama y el humo se transforma en chispas; no usa micrófono.'],['fuegos-con-tu-nombre','Para destacar el nombre: los fuegos se reúnen en letras y después caen como luz dorada.']], advice:'Pastel de cumpleaños muestra velas y confeti automáticamente; sus velas no se apagan al soplar. Globos de cumpleaños mantiene un movimiento continuo y Regalo sorpresa 3D abre una caja. Estas escenas no permiten elegir una edad dentro de su geometría: puedes escribirla en tu mensaje.' },
  navidad: { intro:'El árbol se ilumina solo; la esfera añade una agitación que el destinatario puede activar. Los dos diseños conservan sus luces navideñas y aceptan nombre, frase, firma y tipografía.', picks:[['esfera-de-nieve','Para una sorpresa por toque: se agitan los copos y se enciende la estrella dentro del vidrio.'],['arbol-de-navidad','Para una felicitación sin interacción: las luces recorren el árbol hasta llegar a la estrella.']], advice:'Elige la esfera si quieres que la persona haga un gesto al abrir la felicitación. Elige el árbol si prefieres una secuencia directa. En ambos casos el mensaje se superpone al diseño; no sustituye los adornos ni la estrella.' },
};

CATEGORY_GUIDES.general={intro:'Una ilusión de perspectiva se transforma en un camino ascendente de luz.',picks:[['escalera-imposible','Para celebrar una nueva etapa o compartir ánimo.']],advice:'Toca para cambiar el ángulo o deja que avance. Nombre, mensaje, firma y colores son opcionales.'};

for (const {category,id,description} of TURTLE_ANIMATIONS) { const guide=CATEGORY_GUIDES[category]; if(category!=='general')guide.picks.push([id,description]); }

CATEGORY_GUIDES.halloween.intro='Figuras, arquitectura y hilos de Halloween. Las experiencias de dibujo luminoso tienen transformaciones propias y avanzan automáticamente.';
CATEGORY_GUIDES.halloween.advice='Puedes elegir texto propio, sugerido o Sin texto. Las nuevas experiencias conservan su protagonista y permiten repetir la transformación.';
CATEGORY_GUIDES.cumple.advice+=' La máquina de dulces también permite seleccionar una edad de 1 a 999.';
CATEGORY_GUIDES.muertos.advice+=' El retrato admite una foto local opcional. El bordado es una composición artística original.';
