// Reviewed against the cinematic scene modules, rather than the original brief.
export const RECENT_GUIDES = {
 'mansion-imposible': {
  scene:'La mansión se presenta como una miniatura con nueve habitaciones, ventanas empotradas, balcones y tejados. Las ventanas se iluminan por turnos. Después, los cuartos se separan a distintas profundidades mientras sus escaleras mantienen las conexiones: puedes observar el edificio como un diorama abierto.',
  interaction:'Toca la mansión para adelantar la separación de las habitaciones. Si no intervienes, la transformación comienza sola. Reiniciar vuelve a reunir el edificio y repite el encendido de ventanas; tocar de nuevo reinicia el acontecimiento, sin recargar la página.',
  use:'Para una invitación de Halloween, usa el título como nombre de la reunión y la frase para indicar qué celebráis. La mansión sigue visible al aparecer la dedicatoria. La escena no contiene habitaciones navegables ni enlaces independientes dentro del edificio.',mode:'tap'},
 'telarana-electrica': {
  scene:'Radios y una espiral forman una red con gotas de luz. Los hilos tienen conexiones que transmiten la deformación: el movimiento de una zona afecta a sus vecinas. Una araña articulada acompaña la vibración y se aproxima al lugar señalado; la red permanece como estructura de la composición.',
  interaction:'Toca un punto de la telaraña para iniciar una vibración cerca de él. Mover el puntero cambia ligeramente la perspectiva y la posición que sigue la araña. Sin tocar, se activa una vibración automática. Reiniciar devuelve la red a su estado inicial.',
  use:'Una invitación con ambiente nocturno en la que el gesto forma parte del espectáculo. Los dos colores modifican los acentos de luz, sin borrar los hilos ni sus gotas. El mensaje aparece después de la vibración; no hay una araña que puedas controlar como en un juego.',mode:'tap'},
 'grimorio-tinta-viva': {
  scene:'Un libro con tapas, lomo ornamentado y varias capas de papel se abre sobre un fondo oscuro. La escritura se eleva desde las páginas y forma un volumen de filamentos y superficies de tinta. Las hojas se inclinan en secuencia y la tinta vuelve hacia el libro al terminar el acontecimiento.',
  interaction:'Toca el libro para adelantar el movimiento de las páginas y el cambio de la tinta. La escena también avanza sola. No necesitas arrastrar: la dirección o distancia de un deslizamiento no controla las hojas. Reiniciar permite ver otra vez la apertura completa.',
  use:'Elige una frase breve para presentar una historia de Halloween o invitar a una noche de lectura. Un título corto puede aparecer sobre una página; los títulos largos se colocan con la dedicatoria para conservar la legibilidad. No es un libro de páginas que puedas leer o seleccionar.',mode:'tap'},
 'carrusel-medianoche': {
  scene:'Una cubierta segmentada, luces pequeñas, plataforma y postes componen un carrusel de seis caballos. Las monturas se alejan de los postes y recorren un giro espacial con estelas, mientras el techo y la base conservan la referencia del carrusel. Al concluir, los caballos regresan hacia sus posiciones.',
  interaction:'Toca el carrusel para liberar las monturas antes del inicio automático. Los caballos siguen una coreografía propia; no se elige una montura ni se controla su dirección. Puedes volver a tocar para repetir el acontecimiento o usar Reiniciar para ver la formación inicial.',
  use:'Una invitación festiva con tono de fantasía nocturna. El mensaje acompaña la salida de los caballos sin sustituir el carrusel. Los tonos editables afectan los acentos de la composición; la estructura y los detalles de las monturas siguen conservando sus materiales.',mode:'tap'},
 'catrina-encaje': {
  scene:'La figura de cuerpo entero combina un sombrero amplio con un vestido de pliegues y doce capas de encaje. Al desarrollarse la secuencia, la falda se ensancha y las capas se separan en abanico. Los tejidos siguen visibles alrededor de la silueta cuando aparece el mensaje.',
  interaction:'Mueve el puntero, o arrastra suavemente en la pantalla, para cambiar el ángulo de observación. Un toque adelanta el despliegue de encajes, que también comienza automáticamente. Reiniciar recupera el vestido recogido. No hay recuerdos ni una carta que abrir en esta escena.',
  use:'Para celebrar el Día de Muertos o acompañar un recuerdo con una figura elegante. Puedes elegir una frase propia, nombre y firma, o dejar solo la obra. El movimiento del vestido es una interpretación artística original; no representa una tradición o creencia documentada.',mode:'explore'},
 'pan-memoria': {
  scene:'El pan aparece sobre un plato, con corteza sombreada, relieves y granos de azúcar. Una porción se aparta y permite ver su interior. Desde el corte ascienden cintas de vapor; dentro de ellas se insinúan una mesa y dos sillas, antes de mostrar la dedicatoria.',
  interaction:'Toca el pan para adelantar la separación de la porción. Si esperas, la escena realiza el mismo acontecimiento por sí sola. El toque no envía un enlace: para compartir se utiliza el botón del editor. Reiniciar reúne el pan y vuelve a comenzar la secuencia.',
  use:'Un recuerdo cálido de una mesa compartida o una invitación a reunirse durante el Día de Muertos. El vapor y la pequeña mesa son una composición visual original. La escena no es una receta, y no ofrece corte libre del pan ni selección de ingredientes.',mode:'tap'},
 'retrato-historias': {
  scene:'Un marco ornamentado contiene una habitación en capas: suelo, mesa, dos sillas, objetos y una ventana. El cambio de perspectiva deja ver las distancias entre ellas. Durante la transformación, las capas se separan ligeramente. Si añadiste una foto, aparece dentro del marco; sin foto se conserva la habitación.',
  interaction:'Mueve el puntero o arrastra sobre el retrato para observar la profundidad. Toca para adelantar la transformación y la aparición de la foto, si existe. También avanza automáticamente. No hay fotografías predeterminadas ni objetos con recuerdos individuales para abrir.',
  use:'Una dedicatoria de memoria centrada en un lugar cotidiano. La fotografía es opcional: el editor la recorta y reduce en el dispositivo, y la incluye en el enlace. Usa una imagen que tengas permiso para compartir; cualquier persona con ese enlace puede acceder a ella. No se realiza reconocimiento facial.',mode:'explore'},
 'bordado-memoria': {
  scene:'Una tela oscura con trama, borde ornamentado y motivos florales presenta hilos con relieve. La superficie se ondula y los motivos se elevan como pequeñas piezas conectadas al tejido. Cuando baja la elevación, la composición vuelve a acercarse a la tela y deja el título acompañado por la dedicatoria.',
  interaction:'Mantén pulsado para aumentar la elevación del bordado. Al soltar, el efecto sigue la resolución de la secuencia; no desaparece instantáneamente. Sin intervención también hay un despliegue automático. Reiniciar devuelve la tela y los motivos a su estado inicial.',
  use:'Para coser simbólicamente un nombre o acompañar una memoria con color y textura. No se dibuja libremente con el dedo: los motivos forman parte de una composición artística original. Puedes cambiar los acentos, utilizar una frase propia o elegir Sin texto.',mode:'hold'},
 'herbario-luz': {
  scene:'Un libro abierto sostiene cuatro ejemplares botánicos con tallos, hojas, nervaduras y detalles florales. Una página se inclina y las plantas se levantan a distintas alturas, conservando su forma y relación con el papel. El movimiento secundario de las hojas mantiene el aspecto de ejemplares suspendidos.',
  interaction:'Toca el herbario para adelantar la elevación de la página y los ejemplares. No necesitas deslizar y el arrastre no selecciona páginas. También avanza solo. Reiniciar devuelve las plantas al papel; no hay fichas científicas individuales ni especies seleccionables.',
  use:'Una dedicatoria para alguien que disfruta observar pequeños detalles naturales. El título funciona como una etiqueta de la composición, sin identificar una especie botánica real. La frase y la firma aparecen junto al herbario; los ejemplares siguen visibles.',mode:'tap'},
 'eclipse-corona': {
  scene:'Un disco solar texturizado queda oculto por un disco oscuro. La ocultación permite observar una corona de filamentos curvos, con diferencias de longitud y luz. La superficie del sol desaparece detrás del disco: la atención pasa del cuerpo iluminado a su borde y a la corona.',
  interaction:'Mantén y arrastra para desplazar ligeramente el disco oscuro y comparar la alineación. Al soltar, vuelve a la alineación automática. Un toque adelanta el desarrollo de la corona y el mensaje. No es un simulador astronómico ni predice eclipses reales.',
  use:'Para destacar un momento excepcional, un logro o una pausa compartida. La escena utiliza una representación artística del eclipse; no ofrece instrucciones de observación solar. Los acentos editables conservan el contraste entre ocultación, disco y corona.',mode:'explore'},
 'maquina-dulces': {
  scene:'Una máquina con carcasa, tubos curvos, reflejos de vidrio y bandeja conduce dulces de colores. Las bolitas forman la edad que elijas y después caen hacia la bandeja con pequeños rebotes. Sin edad se utiliza un motivo festivo de siete brazos, en lugar de imponer un número.',
  interaction:'Elige una edad entre 1 y 999 en el editor; no se calcula a partir de una fecha. Toca la máquina para adelantar la caída de dulces o espera a la activación automática. Reiniciar repite el recorrido y la formación con la edad guardada en el enlace.',
  use:'Una felicitación de cumpleaños donde la edad es parte de la figura. Un título breve aparece junto a la bandeja y la frase acompaña la entrega. La máquina es una animación: no reparte productos ni utiliza pagos, premios o sorteos.',mode:'tap'},
 'taller-juguetes': {
  scene:'Un banco de trabajo con brazos articulados reúne las piezas de un pequeño tren: locomotora, cabina y ruedas con radios. Al avanzar la secuencia, el tren sale del taller y se dibuja una vía delante de él. Una tarjeta acompaña la entrega del mensaje mientras el taller mantiene su presencia.',
  interaction:'Toca el taller para adelantar la salida del tren. El ensamblaje y el recorrido también avanzan automáticamente. No puedes conducirlo ni cambiar los rieles; Reiniciar vuelve al montaje de las piezas y repite la entrega.',
  use:'Una felicitación navideña centrada en la fabricación de un juguete de luz. Puedes escribir un saludo familiar sin una frase romántica. La tarjeta y el tren forman parte de la misma secuencia; no se necesita instalar nada para abrir el enlace.',mode:'tap'},
 'guitarra-resonancia': {
  scene:'Una guitarra con caja de madera, vetas, roseta, puente, mástil y clavijas sostiene seis cuerdas. Al activarse, las cuerdas se deforman y aparecen ondas alrededor de la boca del instrumento. La perspectiva y las diferencias de material mantienen visible el cuerpo mientras se revela el texto.',
  interaction:'Mantén pulsado y desliza de lado a lado para hacer vibrar las cuerdas. Mover el puntero también cambia un poco el ángulo. Sin intervención se produce una resonancia automática. Esta versión es visual y no reproduce sonido; Reiniciar repite la secuencia.',
  use:'Para dedicar un saludo musical o compartir una composición de inspiración mexicana. No reproduce una canción ni enseña acordes. El nombre, la frase y la firma acompañan las ondas sin sustituir el instrumento, y los colores editables conservan su textura de madera.',mode:'explore'},
 'escalera-imposible': {
  scene:'Veintiocho escalones con superficie, bordes y soportes crean una ilusión desde el ángulo inicial. La cámara cambia suavemente de perspectiva y hace visibles las separaciones. Después, los tramos se desplazan hasta reunirse en una escalera ascendente, que conserva sus peldaños cuando aparece el mensaje.',
  interaction:'Toca para adelantar el cambio de perspectiva y la conexión de los escalones, o espera a que empiece automáticamente. No se sube por la escalera con controles de juego. Reiniciar recupera la ilusión inicial y permite comparar otra vez ambos puntos de vista.',
  use:'Una frase de ánimo para una nueva etapa o para celebrar un avance. El acontecimiento es la resolución espacial de la ilusión, no una promesa sobre lo que ocurrirá en la vida del destinatario. Puedes dejarla sin texto y conservar únicamente la transformación.',mode:'tap'},
};
