// Browser-native WebGL acceleration for the solid sculptures. The public scene
// still owns a Canvas 2D context, so previews/export/lifecycle need no new API.
export function cineGPU(w,h){
 const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)return null;
 const compile=(type,source)=>{const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;};
 const vs=compile(gl.VERTEX_SHADER,`precision mediump float;attribute vec3 pos;attribute vec3 normal;attribute vec3 col;attribute float material;attribute float size;uniform vec4 view;uniform vec2 angles;uniform vec3 shift;uniform vec3 rotate;uniform vec3 scale;uniform float opacity;uniform float mode;varying vec3 color;varying vec3 norm;varying float mat;varying float alpha;
 vec3 turn(vec3 p,vec3 r){float c=cos(r.x),s=sin(r.x);p=vec3(p.x,p.y*c-p.z*s,p.y*s+p.z*c);c=cos(r.y);s=sin(r.y);p=vec3(p.x*c+p.z*s,p.y,p.z*c-p.x*s);c=cos(r.z);s=sin(r.z);return vec3(p.x*c-p.y*s,p.x*s+p.y*c,p.z);}
 void main(){vec3 p=turn(pos*scale,rotate)+shift;norm=turn(normal,rotate);float c=cos(angles.x),s=sin(angles.x);p=vec3(p.x*c+p.z*s,p.y,p.z*c-p.x*s);c=cos(angles.y);s=sin(angles.y);p=vec3(p.x,p.y*c-p.z*s,p.z*c+p.y*s);float k=4.0/(4.0+p.z);gl_Position=vec4(p.x*view.z*k/view.x*2.0,-p.y*view.z*k/view.y*2.0+1.0-view.w*2.0,(p.z+2.0)/6.0*2.0-1.0-(mode>0.5?0.0005:0.0),1.0);gl_PointSize=max(1.0,size*view.z*k);color=col;mat=material;alpha=opacity*(mode>0.5&&mode<1.5?min(1.0,size*view.z*k):1.0);}`);
 const fs=compile(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 color;varying vec3 norm;varying float mat;varying float alpha;uniform float mode;void main(){float a=alpha;float light=1.0;if(mode<0.5){vec3 n=normalize(norm);float key=abs(dot(n,normalize(vec3(-0.45,-0.7,-0.65))));float rim=pow(abs(dot(n,normalize(vec3(0.8,-0.25,0.5)))),5.0);light=0.25+key*0.68+rim*0.13;if(mat>0.5&&mat<1.5)light=0.22+key*0.48+pow(key,22.0)*0.8+rim*0.35;if(mat>1.5&&mat<2.5)light=0.3+key*0.56+rim*0.20;if(mat>2.5&&mat<3.5)a*=0.24;if(mat>3.5)light=1.15;}if(mode>1.5){float r=length(gl_PointCoord-vec2(0.5));if(r>0.5)discard;a*=1.0-smoothstep(0.2,0.5,r);}gl_FragColor=vec4(color*light,a);}`);
 const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const attrs=[['pos',3,0],['normal',3,12],['col',3,24],['material',1,36],['size',1,40]].map(([name,n,o])=>[gl.getAttribLocation(program,name),n,o]);const uniforms=Object.fromEntries(['view','angles','shift','rotate','scale','opacity','mode'].map(x=>[x,gl.getUniformLocation(program,x)])),cache=new Map(),buffers=new Set();
 const vertex=(out,v,n,c,mat,size=1)=>out.push(...v,...n,c[0]/255,c[1]/255,c[2]/255,mat,size);
 const normal=v=>{const a=v[1].map((x,i)=>x-v[0][i]),b=v[2].map((x,i)=>x-v[0][i]),n=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],l=Math.hypot(...n)||1;return n.map(x=>x/l);};
 const bind=b=>{gl.bindBuffer(gl.ARRAY_BUFFER,b);for(const [loc,n,o] of attrs){gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,44,o);}};
 const store=(entry,key,data)=>{if(!entry[key]){entry[key]=gl.createBuffer();buffers.add(entry[key]);}bind(entry[key]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);entry[key+'Count']=data.length/11;};
 return {canvas,lost:()=>gl.isContextLost(),draw(parts,S,cy,yaw,pitch,color,state){gl.viewport(0,0,w,h);gl.depthMask(true);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.uniform4f(uniforms.view,w,h,S,cy/h);gl.uniform2f(uniforms.angles,yaw,pitch);
  for(const p of parts){if(p.opacity<.001)continue;let entry=cache.get(p);if(!entry){entry={};cache.set(p,entry);}const paletteKey=JSON.stringify([color(0),color(1)]);
   if(entry.faces!==p.faces||entry.palette!==paletteKey||entry.version!==p.materialVersion||p.deform){const data=[];for(const f of p.faces){if(!f.triangles)f.triangles=cineTriangulate(f.v);if(!f.normal)f.normal=normal(f.v);const mat={metal:1,silk:2,glass:3,light:4}[f.material]||0;for(const i of f.triangles){const original=f.v[i],v=p.deform?p.deform(original,state):original;const n=f.normals?.[i]||(f.sphere?original.map((x,k)=>(x-f.sphere[k])/(f.sphere[k+3]*f.sphere[k+3])):f.normal);vertex(data,v,n,color(f.color),mat);}}store(entry,'mesh',data);entry.faces=p.faces;entry.palette=paletteKey;entry.version=p.materialVersion;}
   const lineData=[];for(const l of p.lines)for(let i=1;i<l.v.length;i++)for(const v of [l.v[i-1],l.v[i]])vertex(lineData,p.deform?p.deform(v,state):v,[0,0,1],color(l.color),4,l.width);store(entry,'lines',lineData);
   const pointData=[];for(let i=0;i<p.dots.length;i++){if(state.tier<.6&&i%2)continue;const d=p.dots[i];vertex(pointData,p.dotDeform?p.dotDeform(d,state):p.deform?p.deform(d.v,state):d.v,[0,0,1],color(d.color),4,d.size*2);}store(entry,'points',pointData);
   gl.depthMask(!p.faces.some(f=>f.material==='glass'));gl.uniform3fv(uniforms.shift,p.pos);gl.uniform3fv(uniforms.rotate,p.rot);gl.uniform3fv(uniforms.scale,p.scale);gl.uniform1f(uniforms.opacity,p.opacity);for(const [key,mode,kind] of [['mesh',gl.TRIANGLES,0],['lines',gl.LINES,1],['points',gl.POINTS,2]]){gl.uniform1f(uniforms.mode,kind);bind(entry[key]);gl.drawArrays(mode,0,entry[key+'Count']);}
  }gl.flush();return canvas;},
 dispose(){for(const b of buffers)gl.deleteBuffer(b);cache.clear();gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);gl.getExtension('WEBGL_lose_context')?.loseContext();}
 };
}
function cineTriangulate(v){if(v.length===3)return[0,1,2];if(v.length===4)return[0,1,2,0,2,3];let axes=[0,1],area=0;for(const pair of [[0,1],[0,2],[1,2]]){const n=v.reduce((s,p,i)=>s+p[pair[0]]*v[(i+1)%v.length][pair[1]]-v[(i+1)%v.length][pair[0]]*p[pair[1]],0);if(Math.abs(n)>Math.abs(area)){area=n;axes=pair;}}const q=v.map(p=>axes.map(i=>p[i])),indices=v.map((_,i)=>i),out=[],cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),sign=area>0?1:-1;
 let guard=0;while(indices.length>3&&guard++<v.length*v.length){let found=false;for(let i=0;i<indices.length;i++){const a=indices[(i+indices.length-1)%indices.length],b=indices[i],c=indices[(i+1)%indices.length];if(cross(q[a],q[b],q[c])*sign<=1e-9)continue;const inside=indices.some(j=>j!==a&&j!==b&&j!==c&&cross(q[a],q[b],q[j])*sign>=0&&cross(q[b],q[c],q[j])*sign>=0&&cross(q[c],q[a],q[j])*sign>=0);if(inside)continue;out.push(a,b,c);indices.splice(i,1);found=true;break;}if(!found)break;}if(indices.length===3)out.push(...indices);if(!out.length)for(let i=1;i<v.length-1;i++)out.push(0,i,i+1);return out;}
