import { mkdir, writeFile } from 'node:fs/promises';
import { VISIBLE_ANIMATIONS as animations, CATEGORIES } from '../js/catalog.js';
import { guideFor, MODE_LABELS, relatedAnimations } from '../js/scene-guides.js';
import { CATEGORY_GUIDES } from '../js/category-guides.js';

const origin = 'https://viralcss.com';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const aurl = a => `/animaciones/${a.id}.html`;
const curl = id => `/categorias/${id}.html`;
const edit = a => `/crear.html?a=${a.id}`;
const categories = CATEGORIES.filter(c=>c.id!=='todas' && animations.some(a=>a.category===c.id));
const cname = id => categories.find(c=>c.id===id).name.replace(/^\S+\s/,'');
const particleNames = new Set(['corazon-de-girasoles','flor-holografica','cascada-de-petalos-invertida','corazon-de-energia','constelacion-con-tu-nombre','fuegos-con-tu-nombre']);
const shortNames = new Set(['corazon-de-energia','constelacion-con-tu-nombre','fuegos-con-tu-nombre']);
const options = a => `${a.seasonalText?'Frases o sin texto':a.letterFields?'Carta y recuerdos':'Nombre y mensaje'}${a.colorDefaults?' · Dos colores':''}`;
function card(a) {
 const g=guideFor(a);
 return `<article class="card" data-id="${a.id}" data-mode="${g.mode}" data-color="${!!a.colorDefaults}" data-letter="${!!a.letterFields}"><a class="card-preview-link" href="${aurl(a)}" aria-label="Ver ${esc(a.title)}"><div class="thumb"><canvas aria-hidden="true"></canvas><span class="badge">${MODE_LABELS[g.mode]}</span></div></a><div class="card-body"><h3><a href="${aurl(a)}">${esc(a.title)}</a></h3><p>${esc(a.description)}</p><p class="card-options">${options(a)}</p><div class="card-links"><a href="${aurl(a)}">Ver escena y detalles</a><a href="${edit(a)}">Personalizar<span class="sr-only"> ${esc(a.title)}</span> →</a></div></div></article>`;
}
const controls = `<div class="collection-controls" hidden><label>Buscar por función <select data-filter><option value="all">Todas las escenas</option><option value="auto">Se reproducen solas</option><option value="interactive">Con interacción</option><option value="color">Con colores editables</option><option value="letter">Con carta y recuerdos</option></select></label><button class="btn btn-ghost" type="button" data-motion>Pausar miniaturas</button><p data-count role="status"></p></div>`;
function grid(list) {return `<div class="grid" data-gallery>${list.map(card).join('\n')}</div>`;}
function template({title,description,path,body,schema,script='collection',id=''}) {
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description.slice(0,160))}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description.slice(0,160))}"><meta property="og:image" content="${origin}/img/og.jpg"><meta property="og:url" content="${origin}${path}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#0b1020"><link rel="canonical" href="${origin}${path}"><link rel="icon" href="/img/icon.png" type="image/png"><link rel="stylesheet" href="/css/styles.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body${id?` data-animation="${id}"`:''}><a class="skip-link" href="#contenido">Saltar al contenido</a><header class="site-header"><a class="brand" href="/">Viral<span>Css</span></a><nav aria-label="Navegación principal"><a href="/animaciones.html">Animaciones</a><a href="/acerca.html">Acerca</a><a href="/sugerencias.html">Sugerencias</a></nav></header><main id="contenido" class="container content-page">${body}</main><footer class="site-footer"><span>ViralCss · Crea y comparte una escena</span><div><a href="/acerca.html">Acerca y contacto</a><a href="/privacidad.html">Privacidad</a><a href="/animaciones.html">Todas las animaciones</a></div></footer><script type="module" src="/js/${script}.js"></script><script type="module" src="/js/support.js"></script></body></html>`;
}
function layout(config) {
 return template(config).replace('<a class="brand" href="/">Viral<span>Css</span></a>','<a class="brand" href="/"><img src="/img/logo.png" alt="" width="72" height="48"><span class="brand-name">Viral<span class="accent">Css</span></span></a>').replace(/></g,'>\n<')+'\n';
}
const breadcrumb = entries => ({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:entries.map(([name,url],i)=>({'@type':'ListItem',position:i+1,name,item:origin+url}))});
function personalization(a) {
 const items=[];
 if(a.seasonalText) {
  items.push('Frase sugerida editable, texto propio de hasta 140 caracteres o Sin texto. Esta última opción oculta también el título y la firma.');
  items.push('Título opcional de hasta 40 caracteres: las partículas lo forman después de dispersarse. Sin título, reconstruyen la figura.');
 } else {
  items.push(particleNames.has(a.id)?`Nombre breve: la propia escena forma letras (hasta ${shortNames.has(a.id)?12:32} caracteres dentro de la figura).`:`Nombre y mensaje de hasta 40 y 140 caracteres en el formulario.${a.nameInScene?' La composición también utiliza el nombre; uno breve evita recortes.':''}`);
  items.push(a.id==='origami-amarillo'?'La frase se dibuja dentro de una tarjeta con un máximo de cinco líneas. Conviene probar un mensaje corto.':`Puedes reemplazar la frase inicial «${a.defaultMessage}». Si la dejas vacía, se conserva la sugerencia de esta escena.`);
 }
 items.push('Firma opcional y cinco tipografías para el texto normal. Las letras construidas con partículas conservan su forma.');
 if(a.letterFields) items.push(a.id==='jardin-de-lunas'?'Título y texto de la carta, siete recuerdos y una foto opcional. Los recuerdos acompañan el recorrido por las islas y la carta se abre en el corazón final.':'Título y texto de la carta, y recuerdos separados por el signo |. El destinatario abre la carta al terminar la secuencia.');
 if(a.colorDefaults) items.push('Dos colores opcionales para los elementos de luz. Puedes desactivar la paleta personalizada para recuperar el diseño original; el fondo y algunos detalles mantienen sus colores.');
 return `<ul>${items.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
}
await mkdir('animaciones',{recursive:true}); await mkdir('categorias',{recursive:true});
const catalogBody=`<nav class="breadcrumbs" aria-label="Ruta"><a href="/">Inicio</a> / Animaciones</nav><h1>Elige una escena antes de dedicarla</h1><p class="lead">Compara cómo se mueve, qué gesto necesita y qué puedes editar. Abre su ficha para probarla o entra directamente al editor si ya la conoces.</p><nav class="category-links" aria-label="Categorías">${categories.map(c=>`<a href="${curl(c.id)}">${esc(c.name)}</a>`).join('')}</nav><p>Las escenas automáticas funcionan con solo mirar. Las interactivas responden al toque, a una pulsación mantenida o a varios golpes. Los recorridos con carta requieren más tiempo para llegar al final.</p>${controls}${grid(animations)}`;
await writeFile('animaciones.html',layout({title:'Animaciones para personalizar y compartir | ViralCss',description:'Compara animaciones por interacción, cartas, recuerdos y colores. Prueba cada escena antes de crear y compartir tu dedicatoria.',path:'/animaciones.html',body:catalogBody,schema:breadcrumb([['Inicio','/'],['Animaciones','/animaciones.html']])}));
for(const c of categories) {
 const guide=CATEGORY_GUIDES[c.id]; if(!guide) throw Error(`Falta guía ${c.id}`);
 const list=animations.filter(a=>a.category===c.id);
 const body=`<nav class="breadcrumbs" aria-label="Ruta"><a href="/">Inicio</a> / <a href="/animaciones.html">Animaciones</a> / ${esc(cname(c.id))}</nav><h1>${esc(cname(c.id))}: encuentra tu escena</h1><p class="lead">${esc(guide.intro)}</p><section class="selection-guide"><h2>Cómo elegir</h2><ul>${guide.picks.map(([id,reason])=>{const a=animations.find(a=>a.id===id);if(!a)throw Error(id);return `<li><a href="${aurl(a)}">${esc(a.title)}</a>: ${esc(reason)}</li>`;}).join('')}</ul><p>${esc(guide.advice)}</p></section><h2>Escenas de esta categoría</h2>${controls}${grid(list)}<p><a href="/animaciones.html">Comparar con todas las categorías →</a></p>`;
 await writeFile(`categorias/${c.id}.html`,layout({title:`${cname(c.id)}: escenas, interacción y opciones | ViralCss`,description:guide.intro,path:curl(c.id),body,schema:breadcrumb([['Inicio','/'],['Animaciones','/animaciones.html'],[cname(c.id),curl(c.id)]])}));
}
for(const a of animations) {
 const g=guideFor(a); const interactive=g.mode!=='auto';
 const body=`<nav class="breadcrumbs" aria-label="Ruta"><a href="/">Inicio</a> / <a href="${curl(a.category)}">${esc(cname(a.category))}</a> / ${esc(a.title)}</nav><p class="eyebrow">${esc(cname(a.category))} · ${MODE_LABELS[g.mode]}</p><h1>${esc(a.title)}</h1><p class="lead">${esc(a.description)}</p><p><a class="btn btn-primary" href="${edit(a)}">Personalizar esta escena</a></p><div class="detail-layout"><section class="preview-panel"><h2>Prueba la escena</h2><div class="scene detail-scene"><canvas id="detail-canvas" aria-label="${esc(a.title)}: ${esc(g.interaction)}"${interactive?' tabindex="0" role="button"':''}></canvas><div class="overlay" id="detail-overlay"><span class="ov-to" id="ov-to"></span><p class="ov-msg" id="ov-msg"></p><span class="ov-from" id="ov-from"></span></div><button id="detail-play" class="btn btn-primary" type="button">Cargar vista previa</button></div><div class="preview-controls"><button class="btn btn-ghost" id="detail-pause" hidden type="button">Pausar</button><button class="btn btn-ghost" id="detail-replay" hidden type="button">Reiniciar</button></div><p id="detail-status" class="hint" role="status">La vista previa usa texto de ejemplo. Se carga cuando la solicitas.</p><p>${esc(g.interaction)}</p>${interactive?'<p class="hint">Puedes tocar la escena o usar Intro o Espacio con el lienzo enfocado. En una pulsación mantenida, conserva la tecla presionada.</p>':''}</section><div class="detail-copy"><section><h2>Qué ocurre en la escena</h2><p>${esc(g.scene)}</p></section><section><h2>Qué puedes personalizar</h2>${personalization(a)}</section><section><h2>Qué verá el destinatario</h2><p>${a.letterFields?'El enlace abre la escena y su recorrido con recuerdos. La carta queda disponible al final; el destinatario puede leerla en la misma pantalla.':a.seasonalText?'El enlace muestra la figura, la frase y los colores elegidos. Si seleccionas Sin texto, recibe la animación sin título, mensaje ni firma.':'El enlace abre esta misma animación con tu nombre, frase y firma. No necesita crear una cuenta ni instalar una aplicación.'}</p><p>${esc(g.use)}</p><p>El editor genera un enlace para copiar o compartir por WhatsApp. Quien tenga ese enlace puede abrirlo: evita incluir información privada.</p><a class="btn btn-primary" href="${edit(a)}">Crear con ${esc(a.title)}</a>${!a.noCode&&a.id!=='jardin-de-lunas'?` <a href="/codigo.html?a=${a.id}">Ver opción de código</a>`:''}</section></div></div><section><h2>Otras escenas para comparar</h2>${grid(relatedAnimations(a,animations))}<p><a href="${curl(a.category)}">Ver guía de ${esc(cname(a.category))} →</a></p></section>`;
 await writeFile(`animaciones/${a.id}.html`,layout({title:`${a.title}: vista previa y personalización | ViralCss`,description:g.scene,path:aurl(a),body,id:a.id,script:'detail',schema:breadcrumb([['Inicio','/'],[cname(a.category),curl(a.category)],[a.title,aurl(a)]])}));
}
// Solo páginas públicas de descubrimiento. Editor, código y enlaces personales son utilidades sin indexación.
// Se omite lastmod: regenerar HTML no significa que la escena haya cambiado.
const paths=['/','/animaciones.html',...categories.map(c=>curl(c.id)),...animations.map(aurl),'/acerca.html','/privacidad.html','/sugerencias.html'];
await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`\n  <url><loc>${origin}${p}</loc></url>`).join('')}\n</urlset>\n`);
console.log(`Generadas ${animations.length} fichas y ${categories.length} guías de categorías; ${paths.length} URLs públicas.`);
